console.log(`Executing: const { test, expect } = require('@playwright/test');`);
const { test, expect } = require('@playwright/test');
console.log(`Executing: test('OrangeHRM Login and Add User Test', async ({ page }) => {`);
test('OrangeHRM Login and Add User Test', async ({ page }) => {
console.log(`Executing:   const baseURL = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login';`);
  const baseURL = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login';
console.log(`Executing:   console.log('Navigating to login page');`);
  console.log('Navigating to login page');
console.log(`Executing:   await page.goto(baseURL);`);
  await page.goto(baseURL);
console.log(`Executing:   const usernameFieldXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[1]/div[2]/input[1]';`);
  const usernameFieldXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[1]/div[1]/div[2]/input[1]';
console.log(`Executing:   const passwordFieldXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[2]/div[1]/div[2]/input[1]';`);
  const passwordFieldXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[2]/div[1]/div[2]/input[1]';
console.log(`Executing:   const loginButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[3]/button[1]';`);
  const loginButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/form[1]/div[3]/button[1]';
console.log(`Executing:   const adminButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/aside[1]/nav[1]/div[2]/ul[1]/li[1]/a[1]/span[1]';`);
  const adminButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[1]/aside[1]/nav[1]/div[2]/ul[1]/li[1]/a[1]/span[1]';
console.log(`Executing:   const addButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/button[1]';`);
  const addButtonXPath = '/html[1]/body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/button[1]';
console.log(`Executing:   const successMessageXPath = '//p[@class="oxd-text oxd-text--p oxd-text--toast-message oxd-toast-content-text"]';`);
  const successMessageXPath = '//p[@class="oxd-text oxd-text--p oxd-text--toast-message oxd-toast-content-text"]';
console.log(`Executing:   const userManagementHeaderXPath = '//h6[text()="User Management"]';`);
  const userManagementHeaderXPath = '//h6[text()="User Management"]';
console.log(`Executing:   try {`);
  try {
console.log(`Executing:     console.log('Entering username');`);
    console.log('Entering username');
console.log(`Executing:     await page.locator(usernameFieldXPath).click({ timeout: 5000 });`);
    await page.locator(usernameFieldXPath).click({ timeout: 5000 });
console.log(`Executing:     await page.locator(usernameFieldXPath).fill('Admin', { timeout: 5000 });`);
    await page.locator(usernameFieldXPath).fill('Admin', { timeout: 5000 });
console.log(`Executing:     console.log('Entering password');`);
    console.log('Entering password');
console.log(`Executing:     await page.locator(passwordFieldXPath).fill('admin123', { timeout: 5000 });`);
    await page.locator(passwordFieldXPath).fill('admin123', { timeout: 5000 });
console.log(`Executing:     console.log('Clicking login button');`);
    console.log('Clicking login button');
console.log(`Executing:     await page.locator(loginButtonXPath).click({ timeout: 5000 });`);
    await page.locator(loginButtonXPath).click({ timeout: 5000 });
console.log(`Executing:     console.log('Waiting for Admin button to be visible');`);
    console.log('Waiting for Admin button to be visible');
console.log(`Executing:     await page.locator(adminButtonXPath).isVisible({ timeout: 10000 });`);
    await page.locator(adminButtonXPath).isVisible({ timeout: 10000 });
console.log(`Executing:     console.log('Clicking Admin button');`);
    console.log('Clicking Admin button');
console.log(`Executing:     await page.locator(adminButtonXPath).click({ timeout: 5000 });`);
    await page.locator(adminButtonXPath).click({ timeout: 5000 });
console.log(`Executing:     console.log('Waiting for User Management header to be visible');`);
    console.log('Waiting for User Management header to be visible');
console.log(`Executing:     await page.locator(userManagementHeaderXPath).isVisible({ timeout: 10000 });`);
    await page.locator(userManagementHeaderXPath).isVisible({ timeout: 10000 });
console.log(`Executing:     console.log('Clicking Add button');`);
    console.log('Clicking Add button');
console.log(`Executing:     await page.locator(addButtonXPath).click({ timeout: 5000 });`);
    await page.locator(addButtonXPath).click({ timeout: 5000 });
console.log(`Executing:     console.log('Waiting for success message');`);
    console.log('Waiting for success message');
console.log(`Executing:     await page.locator(successMessageXPath).isVisible({ timeout: 10000 });`);
    await page.locator(successMessageXPath).isVisible({ timeout: 10000 });
console.log(`Executing:     const successMessage = await page.locator(successMessageXPath).textContent();`);
    const successMessage = await page.locator(successMessageXPath).textContent();
console.log(`Executing:     expect(successMessage).toContain('Successfully Saved');`);
    expect(successMessage).toContain('Successfully Saved');
console.log(`Executing:   } catch (error) {`);
  } catch (error) {
console.log(`Executing:     console.error('Test failed:', error);`);
    console.error('Test failed:', error);
console.log(`Executing:     expect(false, 'Test failed with error: ${error.message}').toBe(true);`);
    expect(false, `Test failed with error: ${error.message}`).toBe(true);
  }
console.log(`Executing: });`);
});