services:
  - type: web
    name: playwright-cloud-runner
    env: node
    plan: free
    buildCommand: npm install && npx playwright install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
